# Generated by Django 2.2.19 on 2022-10-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221021_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slub',
            new_name='slug',
        ),
    ]
